import Erdos524.FiniteLaplaceBand

/-! A positive-probability annulus generated by the zero evaluation and a small residual. -/

namespace Erdos524.LaplaceAnnulusGeometry

open Set MeasureTheory ProbabilityTheory
open Erdos524.FiniteLaplaceRegression Erdos524.FiniteLaplaceBand Erdos524.GaussianBoxDensity

variable {n : ℕ}

theorem affine_annulus_subset (u : Fin (n + 1) → ℝ) (hu : ∀ i, 0 ≤ u i)
    (j : Fin (n + 1)) (hj : u j = 0) {a η : ℝ} (ha : 0 ≤ a) (hη : 0 < η) :
    Icc (a + 2 * η) (a + 3 * η) ×ˢ box (fun _ : Fin (n + 1) ↦ η) ⊆
      fiberSet u (a + 4 * η) \ fiberSet u a := by
  intro p hp
  have hG : 0 ≤ p.1 := by linarith [hp.1.1]
  constructor
  · intro i
    have hcoef : 0 ≤ zeroCoefficient (u i) :=
      (Real.exp_pos (-(u i))).le.trans (zeroCoefficient_lower (hu i) le_rfl)
    have hup := mul_le_mul_of_nonneg_right (zeroCoefficient_upper (hu i)) hG
    have hlo := mul_nonneg hcoef hG
    have hr := hp.2 i (Set.mem_univ i)
    rw [abs_le]
    constructor <;> nlinarith [hr.1, hr.2, hp.1.2]
  · intro hold
    have h := (abs_le.mp (hold j)).2
    rw [hj, zeroCoefficient_zero, one_mul] at h
    have hr := hp.2 j (Set.mem_univ j)
    linarith [hr.1, hp.1.1]

end Erdos524.LaplaceAnnulusGeometry
